In [1]:
import numpy as np
import pandas as pd
import lxml

In [3]:
dfs = pd.read_html('https://en.wikipedia.org/wiki/100_metres')

In [6]:
dfs[3]

,Ath.#,Perf.#,Time (s),Wind (m/s),Athlete,Nation,Date,Place,Ref.
0,1.0,1.0,9.58,+0.9,Usain Bolt,Jamaica,16 AUG 2009,Berlin,[25]
1,NaN,2.0,9.63,+1.5,Bolt #2,NaN,05 AUG 2012,London,NaN
2,NaN,3.0,9.69,±0.0,Bolt #3,NaN,16 AUG 2008,Beijing,NaN
3,2.0,3.0,9.69,+2.0,Tyson Gay,United States,20 SEP 2009,Shanghai,[26]
4,2.0,3.0,9.69,−0.1,Yohan Blake,Jamaica,23 AUG 2012,Lausanne,[27]
5,NaN,6.0,9.71,+0.9,Gay #2,NaN,16 AUG 2009,Berlin,[25]
6,NaN,7.0,9.72,+1.7,Bolt #4,NaN,31 MAY 2008,New York City,NaN
7,4.0,7.0,9.72,+0.2,Asafa Powell,Jamaica,02 SEP 2008,Lausanne,[28]
8,NaN,9.0,9.74,+1.7,Powell #2,NaN,09 SEP 2007,Rieti,NaN
9,5.0,9.0,9.74,+0.9,Justin Gatlin,United States,15 MAY 2015,Doha,[29]
10,NaN,11.0,9.75,+1.1,Blake #2,NaN,29 JUN 2012,Kingston,NaN
11,NaN,11.0,9.75,+1.5,Blake #3,NaN,05 AUG 2012,London,NaN
12,NaN,11.0,9.75,+0.9,Gatlin #2,NaN,04 JUN 2015,Rome,NaN
13,NaN,11.0,9.75,+1.4,Gatlin #3,NaN,09 JUL 2015,Lausanne,NaN
14,NaN,15.0,9.76,+1.8,Bolt #5,NaN,03 MAY 2008,Kingston,NaN
15,NaN,15.0,9.76,+1.3,Bolt #6,NaN,16 SEP 2011,Brussels,NaN
16,NaN,15.0,9.76,−0.1,Bolt #7,NaN,31 MAY 2012,Rome,NaN
17,NaN,15.0,9.76,+1.4,Blake #4,NaN,30 AUG 2012,Zürich,NaN
18,6.0,15.0,9.76,+0.6,Christian Coleman,United States,28 SEP 2019,Doha,[30]
19,6.0,15.0,9.76[A],+1.2,Trayvon Bromell,United States,18 SEP 2021,Nairobi,[31]
20,6.0,15.0,9.76,+1.4,Fred Kerley,United States,24 JUN 2022,Eugene,NaN
21,NaN,22.0,9.77,+1.6,Powell #3,NaN,14 JUN 2005,Athens,NaN
22,NaN,22.0,9.77,+1.5,Powell #4,NaN,11 JUN 2006,Gateshead,NaN
23,NaN,22.0,9.77,+1.0,Powell #5,NaN,18 AUG 2006,Zürich,NaN
24,NaN,22.0,9.77,+1.0,Gay #3,NaN,28 JUN 2008,Eugene,NaN
25,NaN,22.0,9.77,−1.3,Bolt #8,NaN,05 SEP 2008,Brussels,NaN
26,NaN,22.0,9.77,+0.9,Powell #6,NaN,07 SEP 2008,Rieti,NaN
27,NaN,22.0,9.77,+0.4,Gay #4,NaN,10 JUL 2009,Rome,NaN
28,NaN,22.0,9.77,−0.3,Bolt #9,NaN,11 AUG 2013,Moscow,NaN
29,NaN,22.0,9.77,+0.6,Gatlin #4,NaN,05 SEP 2014,Brussels,NaN
30,NaN,22.0,9.77,+0.9,Gatlin #5,NaN,23 AUG 2015,Beijing,NaN
31,NaN,22.0,9.77,+1.5,Bromell #2,NaN,05 JUN 2021,Miramar,[32]
32,9.0,22.0,9.77[A],+1.2,Ferdinand Omanyala,Kenya,18 SEP 2021,Nairobi,[31]
33,NaN,22.0,9.77,+1.8,Kerley #2,NaN,24 JUN 2022,Eugene,[33]
34,10.0,NaN,9.78,+0.9,Nesta Carter,Jamaica,29 AUG 2010,Rieti,[34]
35,11.0,NaN,9.79,+0.1,Maurice Greene,United States,16 JUN 1999,Athens,[35]
36,12.0,NaN,9.80,+1.3,Steve Mullings,Jamaica,04 JUN 2011,Eugene,[36]
37,12.0,NaN,9.80,+0.1,Marcell Jacobs,Italy,01 AUG 2021,Tokyo,[37]
38,14.0,NaN,9.82,+1.7,Richard Thompson,Trinidad and Tobago,21 JUN 2014,Port of Spain,[38]
39,15.0,NaN,9.83,+0.9,Su Bingtian,China,01 AUG 2021,Tokyo,NaN
40,15.0,NaN,9.83,+0.9,Ronnie Baker,United States,01 AUG 2021,Tokyo,NaN
41,17.0,NaN,9.84,+0.7,Donovan Bailey,Canada,27 JUL 1996,Atlanta,NaN
42,17.0,NaN,9.84,+0.2,Bruny Surin,Canada,22 AUG 1999,Seville,NaN
43,17.0,NaN,9.84,+1.2,Akani Simbine,South Africa,06 JUL 2021,Székesfehérvár,[39]
44,20.0,NaN,9.85,+1.2,Leroy Burrell,United States,06 JUL 1994,Lausanne,[40]
45,20.0,NaN,9.85,+1.7,Olusoji Fasuba,Nigeria,12 MAY 2006,Doha,NaN
46,20.0,NaN,9.85,+1.3,Mike Rodgers,United States,04 JUN 2011,Eugene,NaN
47,20.0,NaN,9.85,+1.5,Marvin Bracy,United States,05 JUN 2021,Miramar,[32]
48,24.0,NaN,9.86,+1.2,Carl Lewis,United States,25 AUG 1991,Tokyo,[41]
49,24.0,NaN,9.86,−0.4,Frankie Fredericks,Namibia,03 JUL 1996,Lausanne,NaN
50,24.0,NaN,9.86,+1.8,Ato Boldon,Trinidad and Tobago,19 APR 1998,Walnut,NaN
51,24.0,NaN,9.86,+0.6,Francis Obikwelu,Portugal,22 AUG 2004,Athens,NaN
52,24.0,NaN,9.86,+1.4,Keston Bledman,Trinidad and Tobago,23 JUN 2012,Port of Spain,NaN
53,24.0,NaN,9.86,+1.3,Jimmy Vicaut,France,04 JUL 2015,Saint-Denis,[42]
54,24.0,NaN,9.86,+0.9,Noah Lyles,United States,18 MAY 2019,Shanghai,[43]
55,24.0,NaN,9.86,+0.8,Divine Oduduru,Nigeria,07 JUN 2019,Austin,[44]
56,24.0,NaN,9.86,+1.6,Michael Norman,United States,20 JUL 2020,Fort Worth,[45]
57,24.0,NaN,9.86,+0.2,Oblique Seville,Jamaica,21 MAY 2022,Kingston,[46]
58,24.0,NaN,9.86,+0.7,Micah Williams,United States,27 MAY 2022,Fayetteville,[47]